services:
  wlsadmin:
    image: 12213-domain-home-in-image
    entrypoint: ""
    command:
      - sh
      - -c
      - |
        cat <<'EOF'> /u01/oracle/properties/security.properties
        username=myuser
        password=mypassword1
        JAVA_OPTIONS=-Dweblogic.StdoutDebugEnabled=false
        EOF
        exec startAdminServer.sh
    ports:
      - 7001:7001
    healthcheck:
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3
      test: curl -fsSL http://localhost:7001/weblogic/ready
  MS1:
    image: 12213-domain-home-in-image
    environment:
      - MANAGED_SERV_NAME=managed-server1
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8001
    entrypoint: ""
    command:
      - sh
      - -c
      - |
        cat <<'EOF'> /u01/oracle/properties/security.properties
        username=myuser
        password=mypassword1
        JAVA_OPTIONS=-Dweblogic.StdoutDebugEnabled=false
        EOF
        exec startManagedServer.sh
    expose:
      - 8001
    ports:
      - 8001:8001
    healthcheck:
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3
      test: curl -fsSL http://localhost:8001/weblogic/ready
    depends_on:
      wlsadmin:
        condition: service_healthy
  MS2:
    image: 12213-domain-home-in-image
    environment:
      - MANAGED_SERV_NAME=managed-server2
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8001
    entrypoint: ""
    command:
      - sh
      - -c
      - |
        cat <<'EOF'> /u01/oracle/properties/security.properties
        username=myuser
        password=mypassword1
        JAVA_OPTIONS=-Dweblogic.StdoutDebugEnabled=false
        EOF
        exec startManagedServer.sh
    expose:
      - 8001
    ports:
      - 8002:8001
    healthcheck:
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3
      test: curl -fsSL http://localhost:8001/weblogic/ready
    depends_on:
      wlsadmin:
        condition: service_healthy
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    healthcheck:
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3
      test: curl -fsSL http://localhost/weblogic/ready
