volumes:
  wlsadmin: {}
  MS1: {}
  MS2: {}
services:

  wlsadmin:
    image: weblogic-domain-home-in-image
    entrypoint: ""
    command:
      - sh
      - -c
      - |
        cat <<'EOF'> /u01/oracle/properties/security.properties
        username=myuser
        password=mypassword1
        JAVA_OPTIONS=-Dweblogic.StdoutDebugEnabled=false
        EOF
        rm -f /u01/oracle/user_projects/domains/domain1/servers/*/logs/*.log
        exec startAdminServer.sh
    ports:
      - 7001:7001
    healthcheck:
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3
      test: curl -fsSL http://localhost:7001/weblogic/ready
    volumes:
      - wlsadmin:/u01/oracle/user_projects/domains/domain1

  MS1:
    image: weblogic-domain-home-in-image
    environment:
      - MANAGED_SERV_NAME=managed-server1
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8001
    entrypoint: ""
    command:
      - sh
      - -c
      - |
        cat <<'EOF'> /u01/oracle/properties/security.properties
        username=myuser
        password=mypassword1
        JAVA_OPTIONS=-Dweblogic.StdoutDebugEnabled=false
        EOF
        rm -f /u01/oracle/user_projects/domains/domain1/servers/*/logs/*.log
        exec startManagedServer.sh
    expose:
      - 8001
    ports:
      - 8001:8001
    healthcheck:
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3
      test: curl -fsSL http://localhost:8001/weblogic/ready
    depends_on:
      wlsadmin:
        condition: service_healthy
    volumes:
      - MS1:/u01/oracle/user_projects/domains/domain1

  MS2:
    image: weblogic-domain-home-in-image
    environment:
      - MANAGED_SERV_NAME=managed-server2
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8001
    entrypoint: ""
    command:
      - sh
      - -c
      - |
        cat <<'EOF'> /u01/oracle/properties/security.properties
        username=myuser
        password=mypassword1
        JAVA_OPTIONS=-Dweblogic.StdoutDebugEnabled=false
        EOF
        rm -f /u01/oracle/user_projects/domains/domain1/servers/*/logs/*.log
        exec startManagedServer.sh
    expose:
      - 8001
    ports:
      - 8002:8001
    healthcheck:
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3
      test: curl -fsSL http://localhost:8001/weblogic/ready
    depends_on:
      wlsadmin:
        condition: service_healthy
    volumes:
      - MS2:/u01/oracle/user_projects/domains/domain1

  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.5.2-alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    healthcheck:
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3
      test: curl -fsSL http://localhost/weblogic/ready
